name: Test
on:
  pull_request:
    types: [labeled]

jobs:
  patch:
    name: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
  minor:
    name: Minor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
  major:
    name: Major
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
